# Generated by Django 5.1.6 on 2025-06-10 05:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                ("salary", models.IntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Dev", "Developer"),
                            ("HR", "Human Resources"),
                            ("BA", "Business Analyst"),
                            ("PM", "Project Manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enrollTime", models.DateField(default=django.utils.timezone.now)),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="userid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.users",
                    ),
                ),
            ],
        ),
    ]
